---
# yaml 파일을 쪼개고, 합치는 것으로 정리해서 local용과 deployment용을 나눌 수 있을 듯
- hosts: all                                            # hosts 파일에 있는 인벤토리 기반으로 실행
  become: true
  vars:
    mysql_root_pass: skay9954

  tasks:                                                # 실행할 Task들을 지정
    - name: Node 설치 확인
      command: "node --version"
      register: node
      ignore_errors: yes

    - name: "npm Repo Script 실행"
      script: npm.sh
      when: node.rc == 2

    - name: "Node.js 설치"
      apt: name=nodejs

    - name: "Gulp 설치"
      npm:
        name=gulp
        global=yes

    - name: "MySQL 설치"
      apt: name=mysql-server

    - name: "PyMySQL 설치"
      pip: name=PyMySQL

    - name: MySQL Root Account
      mysql_user:                           # insecure 옵션으로 설치했기에 반드시 재설정 필요
        login_unix_socket=/var/run/mysqld/mysqld.sock
        check_implicit_admin=yes
        name=root
        password=rootPassword

    - name: MySQL User Account
      mysql_user:                           # insecure 옵션으로 설치했기에 반드시 재설정 필요
        login_unix_socket=/var/run/mysqld/mysqld.sock
        login_user=root
        login_password=rootPassword
        name=vagrant
        password=userPassword

    - name: DDL Copy
      copy:
        src=database.sql
        dest=/tmp/

    - name: Database DDL 적용
      mysql_db:
        state=import
        name=ongi
        target=/tmp/database.sql
        login_user=root
        login_password=skay9954



